# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: vitalik_indexer
networks:
- id: 1
  start_block: 0
  contracts:
  - name: ECR20
    handler: src/EventHandlers.ts
    events:
    - event: Approval(address indexed owner, address indexed spender, uint256 value)
      field_selection:
        transaction_fields:
          - "transactionIndex"
          - "hash"
          - "to"
          - "from"
        block_fields:
          - "parentHash"
          - "transactionsRoot"
